[0m11:10:55.980032 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d27d60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110314880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110314100>]}


============================== 11:10:55.983232 | 4c022173-166d-46b4-a43b-57d9d0e31e27 ==============================
[0m11:10:55.983232 [info ] [MainThread]: Running with dbt=1.5.0
[0m11:10:55.983612 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/gomes/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m11:10:55.984453 [debug] [MainThread]: Starter project path: /Users/gomes/.pyenv/versions/3.9.16/envs/project9/lib/python3.9/site-packages/dbt/include/starter_project
[0m11:11:39.981381 [error] [MainThread]: Encountered an error:

[0m11:11:39.988027 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/gomes/.pyenv/versions/3.9.16/envs/project9/lib/python3.9/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/gomes/.pyenv/versions/3.9.16/envs/project9/lib/python3.9/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/Users/gomes/.pyenv/versions/3.9.16/envs/project9/lib/python3.9/site-packages/dbt/cli/main.py", line 459, in init
    results = task.run()
  File "/Users/gomes/.pyenv/versions/3.9.16/envs/project9/lib/python3.9/site-packages/dbt/task/init.py", line 304, in run
    adapter = self.ask_for_adapter_choice()
  File "/Users/gomes/.pyenv/versions/3.9.16/envs/project9/lib/python3.9/site-packages/dbt/task/init.py", line 230, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "/Users/gomes/.pyenv/versions/3.9.16/envs/project9/lib/python3.9/site-packages/click/termui.py", line 166, in prompt
    value = prompt_func(prompt)
  File "/Users/gomes/.pyenv/versions/3.9.16/envs/project9/lib/python3.9/site-packages/click/termui.py", line 149, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m11:11:39.989351 [debug] [MainThread]: Command `dbt init` failed at 11:11:39.989116 after 44.03 seconds
[0m11:11:39.990130 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d27d60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110314880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110314c70>]}
[0m11:11:39.990800 [debug] [MainThread]: Flushing usage events
[0m11:12:14.115911 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10288fd60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103c488b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103c48130>]}


============================== 11:12:14.118883 | 40f8f205-5d69-4701-ab1f-8b210cbbfa12 ==============================
[0m11:12:14.118883 [info ] [MainThread]: Running with dbt=1.5.0
[0m11:12:14.119255 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/gomes/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m11:12:14.119876 [debug] [MainThread]: Starter project path: /Users/gomes/.pyenv/versions/3.9.16/envs/project9/lib/python3.9/site-packages/dbt/include/starter_project
[0m11:12:14.124162 [debug] [MainThread]: Command `dbt init` succeeded at 11:12:14.124090 after 0.03 seconds
[0m11:12:14.124373 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10288fd60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103bfa3a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103c5a220>]}
[0m11:12:14.124573 [debug] [MainThread]: Flushing usage events
